### ISSUE TITLE
ask if user is still merging or forgot to release the token

### ISSUE THREAD

**Issue by frederichenry** [renatomrcosta/jeeves-smugglesworth#30]
if you have the token for more then 3 hours let jeeves send you a message if you are still merging

**Comment by renatomrcosta** [comment]
Defining hard-rules for implementation:

- Every hour, on the hour, Jeeves will ask whoever has a token for 3h or longer if they are still merging.
- The same user will be asked again and again, every hour.

Later I can add working hours (so Jeeves doesn't repeat itself), or a flag indicating that a given queue has been warned beforehand. Dunno yet

**Comment by renatomrcosta** [comment]
Shoddily done, adding even more clutter to the code IMHO. Oh well.
